# Generated by Django 5.1.3 on 2024-12-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
